### ISSUE TITLE
database download and storage

### ISSUE THREAD

**Issue by sebdalgarno** [poissonconsulting/fwabc#3]
functions to update/download database and store in known location locally.
remove dan argument from functions
check for updates
following download/update, lookup tables should also be updated and cached

look at bcgov packages for inspiration

**Comment by sebdalgarno** [comment]
also see https://github.com/smnorris/fwakit for pythons function to download data (e.g. what are the urls being used?)

**Comment by smnorris** [comment]
fyi, the data at ftp link I currently use has not been updated with latest data fixes from GeoBC - and they have been busy with QA!  I've let them know - creating a script to automate replication from warehouse to FTP is on their todo list. But for work I'm doing now, I'm going to try loading via WFS via either `bcdata bc2pg` from https://github.com/smnorris/bcdata or https://github.com/pramsey/pgsql-ogr-fdw if I can get it to install

**Comment by sebdalgarno** [comment]
thanks for the info @smnorris ! I haven't yet pushed, but am currently working on a branch that queries the database remotely with the new `bcdata` R package. Given that works nicely, I won't be implementing local data storage/download at this point.
